# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cheese.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cheese.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63heese.proto\x12\ncheesefarm\";\n\x06\x43heese\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.cheesefarm.CheeseType\"5\n\rCheeseRequest\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.cheesefarm.CheeseType*O\n\nCheeseType\x12\x0c\n\x08\x45MMENTAL\x10\x00\x12\x08\n\x04\x42RIE\x10\x01\x12\x0c\n\x08PECORINO\x10\x02\x12\r\n\tROQUEFORT\x10\x03\x12\x0c\n\x08\x43\x41NASTRA\x10\x04\x32G\n\rCheeseService\x12\x36\n\x05Order\x12\x19.cheesefarm.CheeseRequest\x1a\x12.cheesefarm.Cheeseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cheese_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHEESETYPE']._serialized_start=144
  _globals['_CHEESETYPE']._serialized_end=223
  _globals['_CHEESE']._serialized_start=28
  _globals['_CHEESE']._serialized_end=87
  _globals['_CHEESEREQUEST']._serialized_start=89
  _globals['_CHEESEREQUEST']._serialized_end=142
  _globals['_CHEESESERVICE']._serialized_start=225
  _globals['_CHEESESERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
