# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stream_pb2 as stream__pb2


class SoccerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Watch = channel.unary_stream(
        '/stream.Soccer/Watch',
        request_serializer=stream__pb2.Match.SerializeToString,
        response_deserializer=stream__pb2.Video.FromString,
        )


class SoccerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Watch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SoccerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Watch': grpc.unary_stream_rpc_method_handler(
          servicer.Watch,
          request_deserializer=stream__pb2.Match.FromString,
          response_serializer=stream__pb2.Video.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stream.Soccer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
