# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='stream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cstream.proto\x12\x06stream\"\x13\n\x05Match\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x05Video\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x12\n\ndata_shape\x18\x03 \x01(\t23\n\x06Soccer\x12)\n\x05Watch\x12\r.stream.Match\x1a\r.stream.Video\"\x00\x30\x01\x62\x06proto3')
)




_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='stream.Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='stream.Match.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=43,
)


_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='stream.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='stream.Video.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='stream.Video.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_shape', full_name='stream.Video.data_shape', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Match'] = _MATCH
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(
  DESCRIPTOR = _MATCH,
  __module__ = 'stream_pb2'
  # @@protoc_insertion_point(class_scope:stream.Match)
  ))
_sym_db.RegisterMessage(Match)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), dict(
  DESCRIPTOR = _VIDEO,
  __module__ = 'stream_pb2'
  # @@protoc_insertion_point(class_scope:stream.Video)
  ))
_sym_db.RegisterMessage(Video)



_SOCCER = _descriptor.ServiceDescriptor(
  name='Soccer',
  full_name='stream.Soccer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='Watch',
    full_name='stream.Soccer.Watch',
    index=0,
    containing_service=None,
    input_type=_MATCH,
    output_type=_VIDEO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOCCER)

DESCRIPTOR.services_by_name['Soccer'] = _SOCCER

# @@protoc_insertion_point(module_scope)
